### ISSUE TITLE
table의 primary key 의 이름을 table명_id에서 id로 바꿉시다!

### ISSUE THREAD

**Issue by leekyukin** [Bamdoliro/Gati-server#124]
### ❓ Question

학교 DB 시간에 선생님께서 `테이블에 이름이 있는데 왜 id에 테이블 명을 넣니?`라고 말씀하셨습니다.
`{테이블명}_id`에서 그냥 `id`로 바꾸는게 어떨까요?

**Comment by gimhanul** [comment]
[이 글](https://stackoverflow.com/questions/208580/naming-of-id-columns-in-database-tables) 읽어보세염

**Comment by leekyukin** [comment]
복잡한 쿼리문 쓸 때는 `tableName+id` 가 편하겠네요!
