### ISSUE TITLE
좋아요 누르는 API의 Http Moethod는 PUT인가여 POST인가여?

### ISSUE THREAD

**Issue by leekyukin** [Bamdoliro/Gati-server#126]
### ❓ Question

좋아요 누르는 API의 Http Moethod는 PUT인가여 POST인가여?

**Comment by gimhanul** [comment]
수정하는거면 put
생성하는거면 post

내부동작이어케되나요

**Comment by leekyukin** [comment]
좋아요 N:N으로 생성하니까 POST 인데 제가 저번에 짠 로직에는 PUT으로 되어 있어서 여쭤봤습니다

**Comment by leekyukin** [comment]
감솸돠 🙏
