### ISSUE TITLE
Response DTO에도 validation annotation이 필요한가요?

### ISSUE THREAD

**Issue by leekyukin** [Bamdoliro/Gati-server#130]
### ❓ Question

구글링해도 잘안나와서...

**Comment by gimhanul** [comment]
필요도 없고 써도 안 먹습니당
애초에 validation이 `@RequestBody @Valid` 조합으로 써야 동작하니까... response 내려줄 땐 Valid annotation 쓸 마땅한 구석도 없어여

`@Valid` 동작 방식 검색해보시면 좋을 거 같네여
