### ISSUE TITLE
코드리뷰

### ISSUE THREAD

**Issue by wonyongChoi05** [Bamdoliro/Gati-server#139]
### ❓ Question

같은 팀끼리 코드리뷰 하는거 너무 부러워요. 저도 코드리뷰라는걸 해보고싶어요.. 혹시 저도 간간히 코드리뷰 살짝 낑겨봐도 될까요..

@gimhanul @leekyukin

**Comment by gimhanul** [comment]
PR 올라와 있는 거 자유롭게 해주세요~
리뷰는 저희쪽에서도 이득입니당

**Comment by leekyukin** [comment]
노 네버앤딩 스토리
