### ISSUE TITLE
CODEOWNERS 추가

### ISSUE THREAD

**Issue by gimhanul** [Bamdoliro/Gati-server#59]
### ✨ Describe

.github 밑에 CODEOWNERS file을 추가해야 합니당

### ✅ Tasks

- [x] organization team 설정
- [x] CODEOWNERS file 작성

### 🙋🏻 Halmal

PR 보낼 때 reviewer 자동으로 넣어주는 친구라고 하네용
궁금하면 [이거](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) 읽어보시게

**Comment by leekyukin** [comment]
정말 좋은 친구네요 👍🏿
